language: python
python:
  - "3.3"
  - "3.4"
  - "2.7"
  - "2.6"
install:
  - "pip install flake8 isort"
  - "python setup.py install"
before_script:
  - "flake8 facebook"
  - "flake8 test"
  - "isort -rc -c --dont-skip='__init__.py' facebook/"
script: python -m test.test_facebook
env:
      global:
      - FACEBOOK_APP_ID=315250588685380
      - FACEBOOK_SECRET=936f45c831801a62d24493e015d06479
